### ISSUE TITLE
Bot for new user onboarding

### ISSUE THREAD

**Issue by alfl** [TechnologyMasters/ideas#28]
alfl
[13:42] 
We used to have a greeting bot, but it broke.

[13:43] 
Really everyone should get a PM and have to PM back "agree" or something.

**Comment by theetrain** [comment]
Here's a guide that can get us started: https://medium.com/@izzydoesizzy/create-a-slack-bot-that-privately-greets-new-users-in-5-easy-steps-a38eabeabcb5 

Use cases/production levels:

0: Greet new users linking them to code of conduct, direct users to the jobs Github repo and  #showcase channel for self-promotion.
1: Periodically check how long users have been inactive, then do something about that.
2: Accept slash commands from admins to anonymously warn users when they've breached the conduct.
